experiment:
  name: "Churn_Prediction"
  run_name: "avg_monthly_added_v1"
  tags:
    model_type: "XGBoost"
    feature_set: "baseline_numeric_categorical"

preprocessor:
  ignore_features: ['Partner', 'gender', 'MultipleLines', 'MonthlyCharges', 'StreamingMovies', 'StreamingTV']

cv_settings:
  n_splits: 5
  random_state: 42
  
hyperparameters:
  - classifier: ["logistic_regression"]
    classifier__C: [10, 12, 14, 16]
    classifier__solver: ['lbfgs', 'liblinear']
    classifier__penalty: ['l1', 'l2']
  - classifier: ["random_forest"]
    classifier__n_estimators: [400, 500, 600]
    classifier__max_depth: [10, 12, 14]
  - classifier: ["xgboost"]
    classifier__n_estimators: [20, 30, 50, 80]
    classifier__learning_rate: [0.05, 0.1, 0.2]
    classifier__max_depth:: [1, 2]
    classifier__min_child_weight: [1, 5, 10]
  